services:
    _defaults:
        autowire: true
        autoconfigure: true

    sourcecroc.access-control.permission-voter:
        class: SourceCroc\AccessControlBundle\Security\Voter\PermissionVoter
        tags: ['security.voter']
