parameters:
    sourcecroc.access-control.refresh-route: sourcecroc.token.refresh
    sourcecroc.access-control.jwt-secret: '%env(APP_SECRET)%'

#imports:
#    - { resource: services/ }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $jwtSecret: '%sourcecroc.access-control.jwt-secret%'

    SourceCroc\AccessControlBundle\AccessControl: ~

    SourceCroc\AccessControlBundle\Controller\:
        resource: '../../Controller/'

    SourceCroc\AccessControlBundle\Command\:
        resource: '../../Command/'

    sourcecroc.access-control.jwt-service:
        class: SourceCroc\AccessControlBundle\Service\JwtService

    SourceCroc\AccessControlBundle\Service\JwtService:
        alias: sourcecroc.access-control.jwt-service
        public: true

    sourcecroc.access-control.authenticator:
        class: SourceCroc\AccessControlBundle\Security\JwtAuthenticator
        arguments:
            $refreshRoute: '%sourcecroc.access-control.refresh-route%'

    SourceCroc\AccessControlBundle\Security\JwtAuthenticator:
        alias: sourcecroc.access-control.authenticator
        public: true

    sourcecroc.access-control.jwt-signer:
        class: SourceCroc\AccessControlBundle\Security\Token\JwtSigner

    SourceCroc\AccessControlBundle\Security\Token\JwtSigner:
        alias: sourcecroc.access-control.jwt-signer
        public: true
